version: '3'

services:
  statsd_exporter:
    image: prom/statsd-exporter
    ports:
      - "9102:9102"
      - "9125:9125/udp"
    restart: unless-stopped
    command:
      - '--statsd.listen-udp=:9125'
      - '--web.listen-address=:9102'

  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME}'
    depends_on:
      - statsd_exporter

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    restart: unless-stopped
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
